remote_theme: pmarsceill/just-the-docs

aux_links:
  "View our GitHub!":
    - "https://github.com/OmarJabri7/Cycle_Buddy"

search_enabled: true

search:
  heading_level: 1
  rel_url: false
  button: true

footer_content: "Omar Jabri, Chang Liu, Yifan Xie <br /> Distributed by an <a href=\"https://github.com/OmarJabri7/Cycle_Buddy/blob/main/LICENSE\">GNU GPL-3.0 license.</a>"
